Attribute VB_Name = "Constants"
Option Explicit

Public Const REPORT_DATABASE_DLL_NAME As String = "crdb_ado.dll"

Public Const USUARIO_ID_ADMINISTRATOR = 1

'CONTRATOS
Public Const CONTRATO_PRECIO_TIPO_AFIJAR As String = "A"
Public Const CONTRATO_PRECIO_TIPO_PESOS As String = "P"
Public Const CONTRATO_PRECIO_TIPO_DOLARES As String = "D"

Public Const MOVIMIENTO_CEREAL_TIPO_ENTRADA As String = "E"
Public Const MOVIMIENTO_CEREAL_TIPO_ENTRADA_NOMBRE As String = "Carta de Porte - Entrada"
Public Const MOVIMIENTO_CEREAL_TIPO_ENTRADA_NOMBRECORTO As String = "CP Entrada"
Public Const MOVIMIENTO_CEREAL_TIPO_SALIDA As String = "S"
Public Const MOVIMIENTO_CEREAL_TIPO_SALIDA_NOMBRE As String = "Carta de Porte - Salida"
Public Const MOVIMIENTO_CEREAL_TIPO_SALIDA_NOMBRECORTO As String = "CP Salida"
Public Const MOVIMIENTO_CEREAL_TIPO_TRANSFERENCIAINTERNA As String = "T"
Public Const MOVIMIENTO_CEREAL_TIPO_TRANSFERENCIAINTERNA_NOMBRE As String = "Transferencia Interna"
Public Const MOVIMIENTO_CEREAL_TIPO_TRANSFERENCIAINTERNA_NOMBRECORTO As String = "Transf. Int."
Public Const MOVIMIENTO_CEREAL_TIPO_SALIDAPRODUCCION As String = "P"
Public Const MOVIMIENTO_CEREAL_TIPO_SALIDAPRODUCCION_NOMBRE As String = "Salida a Producción"
Public Const MOVIMIENTO_CEREAL_TIPO_SALIDAPRODUCCION_NOMBRECORTO As String = "Salida Prod."
Public Const MOVIMIENTO_CEREAL_TIPO_AJUSTEBAJA As String = "B"
Public Const MOVIMIENTO_CEREAL_TIPO_AJUSTEBAJA_NOMBRE As String = "Ajuste (Baja Stock)"
Public Const MOVIMIENTO_CEREAL_TIPO_AJUSTEBAJA_NOMBRECORTO As String = "Ajuste (Baja)"
Public Const MOVIMIENTO_CEREAL_TIPO_AJUSTESUBE As String = "U"
Public Const MOVIMIENTO_CEREAL_TIPO_AJUSTESUBE_NOMBRE As String = "Ajuste (Sube Stock)"
Public Const MOVIMIENTO_CEREAL_TIPO_AJUSTESUBE_NOMBRECORTO As String = "Ajuste (Sube)"

Public Const MOVIMIENTO_SUBPRODUCTO_TIPO_ENTRADAPRODUCCION As String = "E"
Public Const MOVIMIENTO_SUBPRODUCTO_TIPO_ENTRADAPRODUCCION_NOMBRE As String = "Ingreso por Producción"
Public Const MOVIMIENTO_SUBPRODUCTO_TIPO_ENTRADAPRODUCCION_NOMBRECORTO As String = "Ingreso"
Public Const MOVIMIENTO_SUBPRODUCTO_TIPO_SALIDAVENTA As String = "S"
Public Const MOVIMIENTO_SUBPRODUCTO_TIPO_SALIDAVENTA_NOMBRE As String = "Salida por Venta/Canje"
Public Const MOVIMIENTO_SUBPRODUCTO_TIPO_SALIDAVENTA_NOMBRECORTO As String = "Salida"
Public Const MOVIMIENTO_SUBPRODUCTO_TIPO_AJUSTEBAJA As String = "B"
Public Const MOVIMIENTO_SUBPRODUCTO_TIPO_AJUSTEBAJA_NOMBRE As String = "Ajuste (Baja Stock)"
Public Const MOVIMIENTO_SUBPRODUCTO_TIPO_AJUSTEBAJA_NOMBRECORTO As String = "Ajuste (Baja)"
Public Const MOVIMIENTO_SUBPRODUCTO_TIPO_AJUSTESUBE As String = "U"
Public Const MOVIMIENTO_SUBPRODUCTO_TIPO_AJUSTESUBE_NOMBRE As String = "Ajuste (Sube Stock)"
Public Const MOVIMIENTO_SUBPRODUCTO_TIPO_AJUSTESUBE_NOMBRECORTO As String = "Ajuste (Sube)"

'CALCULO DE SERVICIOS
Public Const FLETE_CALCULO_TIPO_EXACTO As String = "EX"
Public Const FLETE_CALCULO_TIPO_FRACCION As String = "FR"

Public Const ALMACENAJE_TIPO_DIAS_GRACIA_FIJO As String = "D"
Public Const ALMACENAJE_TIPO_DIAS_GRACIA_SI_RETIRA_ANTES As String = "G"
Public Const ALMACENAJE_TIPO_FECHA_FIJA As String = "F"

Public Const CEREAL_TARIFA_SECADO_REDONDEOPUNTO_TIPO_NINGUNO As String = "N"  'NO REDONDEA, CALCULA CON LA FRACCIÓN
Public Const CEREAL_TARIFA_SECADO_REDONDEOPUNTO_TIPO_ENTERO As String = "E"   'REDONDEA HASTA 0.4 AL ENTERO MENOR, DESPUÉS AL ENTERO SIGUIENTE
Public Const CEREAL_TARIFA_SECADO_REDONDEOPUNTO_TIPO_SUPERIOR As String = "S"    'REDONDEA AL ENTERO SUPERIOR
Public Const CEREAL_TARIFA_SECADO_REDONDEOPUNTO_TIPO_INFERIOR As String = "I"    'REDONDEA AL ENTERO INFERIOR

Public Const CEREAL_TARIFA_SECADO_TIPO_FIJA As String = "F"     'NO UTILIZA ESCALA, ESPECIFICA UN IMPORTE FIJO PARA TODOS LOS PUNTOS
Public Const CEREAL_TARIFA_SECADO_TIPO_ESCALA As String = "E"   'UTILIZA LAS ESCALAS

Public Const CEREAL_TARIFA_SECADO_TIPO_ESCALA_PORPUNTO As String = "P"          'BUSCA EN LA ESCALA Y APLICA LA TARIFA CORRESPONDIENTE A CADA RANGO DE PUNTOS
Public Const CEREAL_TARIFA_SECADO_TIPO_ESCALA_COMPLETA As String = "C"          'BUSCA EN LA ESCALA Y APLICA LA MISMA TARIFA PARA TODOS LOS PUNTOS
Public Const CEREAL_TARIFA_SECADO_TIPO_ESCALA_FIJO_SECADO As String = "S"       'BUSCA EN LA ESCALA Y COBRA DIRECTAMENTE EL IMPORTE ENCONTRADO SIN CONTAR LOS PUNTOS
Public Const CEREAL_TARIFA_SECADO_TIPO_ESCALA_FIJO_SECADOYZARANDEO As String = "Z"      'BUSCA EN LA ESCALA Y COBRA DIRECTAMENTE EL IMPORTE ENCONTRADO EN CONCEPTO DE SECADO Y ZARANDEO
Public Const CEREAL_TARIFA_SECADO_TIPO_ESCALA_FIJO_TODOCONCEPTO As String = "T" 'BUSCA EN LA ESCALA Y COBRA DIRECTAMENTE EL IMPORTE ENCONTRADO POR TODO CONCEPTO (NO COBRA PARITARIA, ZARANDEO, FUMIGADO Y MEZCLA)

'SITUACION EN REFOG
Public Const REFOG_SITUACION_INEXISTENTE As String = "I"
Public Const REFOG_SITUACION_INEXISTENTE_NOMBRE As String = "Inexistente"
Public Const REFOG_SITUACION_ACTIVO As String = "A"
Public Const REFOG_SITUACION_ACTIVO_NOMBRE As String = "Activo"
Public Const REFOG_SITUACION_EXCLUIDO As String = "E"
Public Const REFOG_SITUACION_EXCLUIDO_NOMBRE As String = "Excluido"
Public Const REFOG_SITUACION_SUSPENDIDO As String = "S"
Public Const REFOG_SITUACION_SUSPENDIDO_NOMBRE As String = "Suspensión Incorrecta Conducta Fiscal"

'FORMULARIOS
Public Const FORMULARIO_RT_RETIRO As String = "R"
Public Const FORMULARIO_RT_RETIRO_NOMBRE As String = "Retiro"
Public Const FORMULARIO_RT_TRANSFERENCIA As String = "T"
Public Const FORMULARIO_RT_TRANSFERENCIA_NOMBRE As String = "Transferencia"

Public Const FORMULARIO_B_COMPRAVENTA As String = "V"
Public Const FORMULARIO_B_COMPRAVENTA_NOMBRE As String = "Compra/Venta"
Public Const FORMULARIO_B_CANJE As String = "C"
Public Const FORMULARIO_B_CANJE_NOMBRE As String = "Canje"

'LIBRO DE MOVIMIENTOS
Public Const LIBRO_MOVIMIENTOTIPO_SALDO_LIBROANTERIOR As String = "L"
Public Const LIBRO_MOVIMIENTOTIPO_SALDO_FOLIOANTERIOR As String = "F"
Public Const LIBRO_MOVIMIENTOTIPO_INGRESO As String = "I"
Public Const LIBRO_MOVIMIENTOTIPO_EGRESO As String = "E"
Public Const LIBRO_MOVIMIENTOTIPO_CIERREDIARIO As String = "D"
Public Const LIBRO_MOVIMIENTOTIPO_CIERREMENSUAL As String = "M"

Public Const LIBRO_REMITENTEDESTINATARIO_CIERREDIARIO_LEGEND As String = "CIERRE DIARIO"
Public Const LIBRO_REMITENTEDESTINATARIO_CIERREMENSUAL_LEGEND As String = "CIERRE MENSUAL"

Public Const LIBRO_OBSERVACIONES_STOCKFOLIOANTERIOR_LEGEND As String = "Stock Libro Anterior"
Public Const LIBRO_OBSERVACIONES_SINMOVIMIENTOS_LEGEND As String = "SIN MOVIMIENTOS"

'REPORTES
Public Const REPORT_FILE_EXTENSION As String = "rpt"
Public Const REPORT_PARAMETER_KEY As String = "@KEY"
Public Const REPORT_PARAMETER_SELECTION As String = "@SEL"
